### ISSUE TITLE
buildTools does not pay attention to overrides

### ISSUE THREAD

**Issue by locallycompact** [srid/haskell-flake#22]
Here if I do something like

```
              haskellPackages = pkgs'.haskell.packages.ghc942;
              buildTools = hp: {
                cabal-doctest = null;
                cabal-install = null;
                ghcid = null;
                haskell-language-server = null;
                hedgehog = null;
                hlint = pkgs'.haskell.packages.ghc942.hlint;
                hoogle = null;
                hoogle-with-packages = null;
                warp = null;
              };
              source-overrides = { };
              overrides = final: prev:
                with pkgs.haskell.lib;
                (horizon-plutus.packages.x86_64-linux) //
                {
                };
            };
```

it does not pay attention to the overrides in horizon, but uses versions of base-compat that I am not sure where they are coming from

```
      > base >=4.3 && <4.16
       >
       For full logs, run 'nix log /nix/store/hqacgvv9lkn11nak8lk8s8j3ndlk7rj6-base-compat-0.11.2.drv'.
```

**Comment by srid** [comment]
I think this is a limitation with `developPackage` we inherit. The plan, in #7, is to stop using `developPackage` and use instead the low-level functions for Haskell from nixpkgs. By doing so, I believe we should be able to resolve this issue as well. 

Alternative, we may upstream a fix to nixpkgs fixing `developPackage` itself.

**Comment by srid** [comment]
I think this is a limitation of using `developPackage`, because that abstraction just doesn't give us the needed glanularity. The plan, in #7, is to stop using `developPackage` and use instead the low-level functions for Haskell from nixpkgs. By doing so, I believe we should be able to resolve this issue as well. 

Alternatively, we may upstream a change to nixpkgs itself changing its `developPackage` to accept a `buildTools` and have it use the overridden package set.

**Comment by srid** [comment]
@locallycompact Could you test #23? Use `"github:srid/haskell-flake/srid/break-developPackage"` as flake input.
