### ISSUE TITLE
Enable `buildFromSdist` by default - to ensure release-worthiness

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#262]
https://community.flake.parts/haskell-flake/settings#buildfromsdist

@roberth made a good point [here](https://github.com/srid/haskell-flake/pull/220#issuecomment-1918850608):

> haskell-flake has a role in CI to ensure release-worthiness. Building from sdist is an important part of that.

Currently, enabling `buildFromSdist` break things (see #253). But we should a) add tests for those (one exists for `jailbreak`, we need another one for `check`), b) find the root cause and fix the breakage, and c) re-enable it as the default.

**Comment by srid** [comment]
Release-worthiness is not the only benefit; building from sdist also avoids unnecessary rebuilds, which otherwise has to be hacked around with source filtering!

<img width="407" alt="image" src="https://github.com/srid/haskell-flake/assets/3998/b9fa8022-23b2-46eb-b503-a496f6f38a32">

So we must definitely do this.

**Comment by roberth** [comment]
> avoids unnecessary rebuilds

Only if content addressed derivations were to be used, which are not a production ready feature yet.

You could emulate it with IFD though, building and unpacking the sdist, `readDir` the output, and then reassemble it with a custom source filter or filesets. This will be slow, because whereas `cabal2nix` is almost instance, `sdist` can take a while, especially if it's generic, `Setup.hs`-based instead of the quicker `cabal-install` one which doesn't work for everyone (horizon-haskell? static?).

**Comment by srid** [comment]
Right, sadly, I notice that rebuilds will happen regardless of the use of `fromSdist`. Change `./subdir/README.md` - then `./subdir/subdir.cabal` Haskell package will rebuild, despite the README.md not being used in the sdist. What's the normal way to fix this?

**Comment by roberth** [comment]
I get by with this:

- Make sure all packages have their own subdir
- If you can get away with it, don't put "unnecessary" files in them
- Maybe accept that some files trigger a rebuild. In my experience, rebuilding for something `README.md` is not great, but not terrible.
- If needed, use a source filter, such as filesets

`README.md` is an interesting one btw. It *should* be part of the sdist, so that Hackage can show it, but it's probably not needed for the build.

I wouldn't be surprised if [haskell.nix](https://github.com/input-output-hk/haskell.nix) has a custom reimplementation of cabal's default sdist behavior in pure Nix.

Something that might be a bit helpful to get the source filter right, is to compare the filtered sources to the sdists in the `checks` output. For a special case like `README.md` where you want it in the sdist, it would help to have e.g. two filesets
- `buildSrc`: exactly what we pass to the derivation
- `extraSdist`: extra files needed for the sdist. When generating the sdist for checking, we pass `toSource { fileset = unions [ buildSrc extraSdist ]; }`.

It's a bit convoluted, but this approach seems to at least guide the user somewhat to get it right and have no surprises at release time. Using ca-derivations would be simpler, but doesn't actually solve the `extraSdist` problem.

**Comment by srid** [comment]
Turned out to be useful: 

https://github.com/srid/haskell-template/pull/129

Though, not all projects need it; for eg., https://github.com/nammayatri/nammayatri does not, as there are no plans to put it on Hackage.
