### ISSUE TITLE
cabal file in project root is not detected

### ISSUE THREAD

**Issue by roberth** [srid/haskell-flake#49]
Encountered this in https://github.com/hercules-ci/arion

`haskellPathsInDir` only scans subdirectories: "${x}/${x}.cabal"

We should also try `${x}.cabal` (regardless of parent directory name, which is impure; store path or lazy tree).

**Comment by srid** [comment]
[Trying to describe this issue in detail]

The `haskellProjects.foo.packages` option currently uses the [`haskellPathsInDir` function](https://github.com/NixOS/nixpkgs/blob/853288c39d7955d38bfe72a67be1db6b74078287/lib/filesystem.nix#L11-L18) from nipxkgs to determine its default value:

https://github.com/srid/haskell-flake/blob/380bffdba536ffd6379b236b2bf227985113cc5c/flake-module.nix#L119-L122

This works for projects with *multiple* local packages (like https://github.com/srid/haskell-multi-nix) where cabal files live at `*/*.cabal`. However, we want the default value to also work for single-package haskell projects (like https://github.com/srid/haskell-template), such that the three lines [here](https://github.com/srid/haskell-template/blob/12ec81a94f34a37e99591f9853e9816d0a404652/flake.nix#L25-L27) can be removed and the flake still works, because the default will recognize it.

**Comment by roberth** [comment]
`haskellPathsInDir` didn't really work for `hercules-ci-agent` either, because that project has an integration test driver in a sub-subdirectory; depth 2, which, like depth 0, isn't depth 1.

https://github.com/hercules-ci/hercules-ci-agent/blob/40d5243b4ea4ecedbf021b50272dc0937a2ad4df/flake.nix#L293-L296

So my workaround was to use `lib.mkOptionDefault`, to extend the default, which is quite a fragile solution that I think most users won't be able to figure out, and shouldn't have to.

The package was listed in a `cabal.project` file, so if we could support that, I think we could have a fairly robust solution without having to scan deeply, which could be slow in monorepos.

The algorithm would then be roughly: check for `cabal.project` or `stack.yaml` or `*.cabal` in the root and use that to set the `packages` option; if not present, require the user to set that option (or some helper option that sets it, for instance an option that specifies the location of a `cabal.project` file).
This change breaks projects that don't have a `cabal.project` and rely on the `*/*.cabal` behavior that we have now. They'll be in the same spot that new users are who haven't really configured their `haskellProjects.x` yet: an empty `packages`, which we can handle by presenting an error message that explains which options can be used to set `packages`.

**Comment by srid** [comment]
> The algorithm would then be roughly: check for `cabal.project` or `stack.yaml` or `*.cabal` in the root and use that to set the `packages` option; if not present, require the user to set that option (or some helper option that sets it, for instance an option that specifies the location of a `cabal.project` file).

This sounds good to me.

- Is there a `cabal.project` parser for Nix already?
- For now, I think, we could just make the default recognize `*.cabal` in addition to `*/*.cabal`; before getting to implementing this idea (unless the parser is already available?) as it would help #69

**Comment by roberth** [comment]
Haskell.nix [has one](https://github.com/input-output-hk/haskell.nix/blob/a30665693a1991341d067df55bbf2bec1124bddd/lib/cabal-project-parser.nix), but I don't know how easily reused it is. Maybe the relevant paths can be found without much effort, I don't know.
Dream2nix works with [different files](https://github.com/nix-community/dream2nix/blob/main/docs/src/subsystems/haskell.md) it seems. Maybe those contain all the needed info, but I don't think we should require them.

**Comment by roberth** [comment]
> * For now, I think, we could just make the default recognize `*.cabal` in addition to `*/*.cabal` before getting to implementing this idea

Yeah, one step at a time. We want to support this case anyway, regardless of `cabal.project` plans.
