### ISSUE TITLE
Group package set related options

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#72]
_Detached from https://github.com/srid/haskell-flake/issues/52#issuecomment-1419754730_

```nix
haskellProjects.foo = {
  devShell.enable = false;
  packageSet = {
    # The overlays are composed in the order they are shown here.
    base = pkgs.haskell.packages.ghc944;
    local = {
      mypkg.root = ./.;  # Assumes mypkg.cabal
    };
    source-overrides = { .. }; # Overrides by direct path to source
    overrides = self: super:  { .. };  # Raw Haskell overlay
  };
};
```

Users can then use `config.haskellPackages.foo.packageSet.final` to access all the packages. The idea is that we can say "start from `base`", then we apply `local`, then `source-overrides` and finally `overrides`, before creating the project specific haskell package set.

`finalPackages` of #68 would become `packageSet.final`.

**Comment by roberth** [comment]
I'm not convinced yet, because it makes the syntax a little bit more complicated. I think of a haskellProject as a package set, and if I need more than one package set, I need to use multiple projects anyway.

We don't have a module for warnings / assertions support yet, but that could be added in flake-parts.

**Comment by srid** [comment]
> because it makes the syntax a little bit more complicated. I think of a haskellProject as a package set, and if I need more than one package set, I need to use multiple projects anyway.

That's fair.
